language: ruby
rvm:
- 2.3.5
deploy:
  provider: heroku
  api_key:
    secure: oLj9hOldDe1AH86k48t9rzeE6GlKbg/mNJ3MN5Did+MiIDe9w+Tsg6wUCT50sfAjtWfvHC+tKw+lVU3GPhQrFVwPUWkabnp0fbe1w29xjJL5d2X6mbeYyIounzHoSqErSqZxUotEjMYf/xq+X4AJL4DTG9LRvmPJ1B6NW2bXke88RGl6Ihah1fgauLlu4qX9rJ3avXBLVofPgzVenYpwJ5alSvhomSq2u1WoDS2fT2G1CnBHPoRrCx96dfhv2bV6GHLRqRuDMuHIlrOyZZ/UK9qKAVNEKUTMuRVcTWOU5sa3mQ7mMUU4lNo/yystG16JGl3WvhUPfiZH9aqdgP2b+ZS/0wYKZlvO6Ne1UsfY5pz62St57AkoswuiW8U56ruiU9VFRHzKtjH0OQBzSFlE97akq6kbA2pZ7BdAMrynfi2Tfj98BtrQOi9e/pGMdd4JuHLm0OpWqPFpjmqC10pbDSrE+jffYiWv//HQUcyaJqO2Hg7614ML4TrzEz3cJGT86MzX/OGPQsLoHziwJaUJ2qCuJ0lFQri69e4eAns02Sx83c4CCrNVn30gu4O4FRW3KzmJLMTpB4n0LMSHeYP7NA9Tq7MGd53FMxU8zr4Ncm+ji134jky60X3CwEWKb9szJy4iS+/86Ejp/0VJP051Va5dn5UIqu+WJSfKmc9RR1Q=
  app: rails-blog-webapp-dev
  run:
    - "rake db:migrate"
    - restart

